name: CI

on:
  push:
    branches: [main]
  pull_request:

jobs:
  macos:
    runs-on: macos-15
    steps:
      - uses: actions/checkout@v5
      - name: Swift version
        run: swift --version
      - name: Build
        run: swift build -v
      - name: Test
        run: swift test -v

  linux:
    runs-on: ubuntu-latest
    container: swift:6.0
    steps:
      - uses: actions/checkout@v5
      - name: Swift version
        run: swift --version
      - name: Build
        run: swift build -v
      - name: Test
        run: swift test -v
